const PUSH_NEW_OFFER = 'PUSH_NEW_OFFER'
const USER_NOTIFY_NO_OFFERS = 'USER_NOTIFY_NO_OFFERS'
const USER_NOTIFY_NEW_OFFERS = 'USER_NOTIFY_NEW_OFFERS'
const USER_NOTIFY_OFFER_CANCELED = 'USER_NOTIFY_OFFER_CANCELED'
const RESTAURANT_PUSH_NEW_ORDER = 'RESTAURANT_PUSH_NEW_ORDER'
const RESTAURANT_PUSH_NEW_ACTIVE = 'RESTAURANT_PUSH_NEW_ACTIVE'

const TELEGRAM_NOTIFY_NEW_ORDER = 'TELEGRAM_NOTIFY_NEW_ORDER'
const TELEGRAM_NOTIFY_DELIVERED = 'TELEGRAM_NOTIFY_DELIVERED'
const TELEGRAM_NOTIFY_NEW_ACTIVE = 'TELEGRAM_NOTIFY_NEW_ACTIVE'

const TELEGRAM_NOTIFY_NEGATIVE_BALANCE = 'TELEGRAM_NOTIFY_NEGATIVE_BALANCE'
const TELEGRAM_NOTIFY_BALANCE_CHANGED = 'TELEGRAM_NOTIFY_BALANCE_CHANGED'

module.exports = {
  PUSH_NEW_OFFER,
  USER_NOTIFY_NO_OFFERS,
  USER_NOTIFY_NEW_OFFERS,
  USER_NOTIFY_OFFER_CANCELED,

  RESTAURANT_PUSH_NEW_ORDER,
  RESTAURANT_PUSH_NEW_ACTIVE,

  TELEGRAM_NOTIFY_NEW_ORDER,
  TELEGRAM_NOTIFY_DELIVERED,
  TELEGRAM_NOTIFY_NEW_ACTIVE,

  TELEGRAM_NOTIFY_NEGATIVE_BALANCE,
  TELEGRAM_NOTIFY_BALANCE_CHANGED
}
